// @generated by protoc-gen-connect-es v1.6.1
// @generated from file weathercontrol.proto (package weathercontrol.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetWeatherRequest, GetWeatherResponse, SetWeatherRequest, SetWeatherResponse } from "./weathercontrol_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service weathercontrol.v1.WeatherControlService
 */
export declare const WeatherControlService: {
  readonly typeName: "weathercontrol.v1.WeatherControlService",
  readonly methods: {
    /**
     * Selects the latest weather that has been set, or a default of {"Sunny", 1}
     *
     * @generated from rpc weathercontrol.v1.WeatherControlService.GetWeather
     */
    readonly getWeather: {
      readonly name: "GetWeather",
      readonly I: typeof GetWeatherRequest,
      readonly O: typeof GetWeatherResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Adds a new weather to the database
     *
     * @generated from rpc weathercontrol.v1.WeatherControlService.SetWeather
     */
    readonly setWeather: {
      readonly name: "SetWeather",
      readonly I: typeof SetWeatherRequest,
      readonly O: typeof SetWeatherResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

