// @generated by protoc-gen-connect-es v1.6.1
// @generated from file weathercontrol.proto (package weathercontrol.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetWeatherRequest, GetWeatherResponse, SetWeatherRequest, SetWeatherResponse } from "./weathercontrol_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service weathercontrol.v1.WeatherControlService
 */
export const WeatherControlService = {
  typeName: "weathercontrol.v1.WeatherControlService",
  methods: {
    /**
     * Selects the latest weather that has been set, or a default of {"Sunny", 1}
     *
     * @generated from rpc weathercontrol.v1.WeatherControlService.GetWeather
     */
    getWeather: {
      name: "GetWeather",
      I: GetWeatherRequest,
      O: GetWeatherResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds a new weather to the database
     *
     * @generated from rpc weathercontrol.v1.WeatherControlService.SetWeather
     */
    setWeather: {
      name: "SetWeather",
      I: SetWeatherRequest,
      O: SetWeatherResponse,
      kind: MethodKind.Unary,
    },
  }
};

