// @generated by protoc-gen-es v1.10.0
// @generated from file weathercontrol.proto (package weathercontrol.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message weathercontrol.v1.GetWeatherRequest
 */
export const GetWeatherRequest = /*@__PURE__*/ proto3.makeMessageType(
  "weathercontrol.v1.GetWeatherRequest",
  [],
);

/**
 * @generated from message weathercontrol.v1.GetWeatherResponse
 */
export const GetWeatherResponse = /*@__PURE__*/ proto3.makeMessageType(
  "weathercontrol.v1.GetWeatherResponse",
  () => [
    { no: 1, name: "weather_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "intensity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message weathercontrol.v1.SetWeatherRequest
 */
export const SetWeatherRequest = /*@__PURE__*/ proto3.makeMessageType(
  "weathercontrol.v1.SetWeatherRequest",
  () => [
    { no: 1, name: "weather_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "intensity", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message weathercontrol.v1.SetWeatherResponse
 */
export const SetWeatherResponse = /*@__PURE__*/ proto3.makeMessageType(
  "weathercontrol.v1.SetWeatherResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

